src/Web/ViewComponents/CategoryListViewComponent.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Interfaces;
using Web.ViewModels;

namespace Web.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private readonly IAsyncRepository<Category> _categoryRepository;

        public CategoryListViewComponent(IAsyncRepository<Category> categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(new CategoryListViewModel(await _categoryRepository.ListAllAsync()));
        }
    }
}

src/Web/ViewComponents/NavbarBasketViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Interfaces;

namespace Web.ViewComponents
{
    public class NavbarBasketViewComponent : ViewComponent
    {
        private readonly IBasketViewModelService _basketViewModelService;

        public NavbarBasketViewComponent(IBasketViewModelService basketViewModelService)
        {
            _basketViewModelService = basketViewModelService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _basketViewModelService.GetNavbarBasketViewModelAsync());
        }
    }
}

src/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />
    <link href="~/css/custom.css" rel="stylesheet" />
</head>
<body>

    <div class="home page-wrapper">
        <header class="header">

            @await Html.PartialAsync("_LayoutHeaderPartial")
        </header>

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="footer bg-white">

            @await Html.PartialAsync("_LayoutFooterPartial")

        </footer><!-- End .footer -->
    </div><!-- End .page-wrapper -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Web/Views/Shared/_LayoutCaraouselPartial.cshtml
<div id="carouselExampleIndicators" class="row carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/img/Carousel-Pics/Coffee-Beans.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/img/Carousel-Pics/Coffee-Store.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/img/Carousel-Pics/Coffee-Cookies.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

src/Web/Views/Shared/_LayoutFooterPartial.cshtml
<!-- Start Footer -->
<footer id="tempaltemo_footer" style="background-color: #d6b98d;">
    <div class="container">
        <div class="row">

            <div class="col-md-4 pt-5">
                <h2 class="h2 border-bottom pb-3">İLETİŞİM</h2>
                <ul class="list-unstyled footer-link-list">
                    <li>
                        <i class="fas fa-map-marker-alt fa-fw"></i>
                        254/6 Sokak No:1/A Keçiören / ANKARA
                    </li>
                    <li>
                        <i class="fa fa-phone fa-fw"></i>
                        <a class="text-decoration-none" href="#">0 585 589 58 58</a>
                    </li>
                    <li>
                        <i class="fa fa-envelope fa-fw"></i>
                        <a class="text-decoration-none" href="mailto:info@kahve.com">info@kahve.com</a>
                    </li>
                </ul>
            </div>

            <div class="col-md-4 pt-5">
                <h2 class="h2 border-bottom pb-3">ÜRÜNLER</h2>
                <ul class="list-group">
                    @await Component.InvokeAsync("CategoryList")
                </ul>
            </div>

            <div class="col-md-4 pt-5">
                <h2 class="h2 border-bottom pb-3">Further Info</h2>
                <ul class="list-unstyled text-light footer-link-list">
                    <li><a class="text-decoration-none" href="#">Home</a></li>
                    <li><a class="text-decoration-none" href="#">About Us</a></li>
                    <li><a class="text-decoration-none" href="#">Shop Locations</a></li>
                    <li><a class="text-decoration-none" href="#">FAQs</a></li>
                    <li><a class="text-decoration-none" href="#">Contact</a></li>
                </ul>
            </div>

        </div>

        <div class="row mb-4">
            <div class="col-12 mb-3">
                <div class="w-100 my-3 border-top border-light"></div>
            </div>
            <div class="col-auto me-auto">
                <ul class="list-inline text-left footer-icons">
                    <li class="list-inline-item rounded-circle text-center">
                        <a><i class="fab fa-facebook-f fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item rounded-circle text-center">
                        <a><i class="fab fa-instagram fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item rounded-circle text-center">
                        <a><i class="fab fa-twitter fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item rounded-circle text-center">
                        <a><i class="fab fa-linkedin fa-lg fa-fw"></i></a>
                    </li>
                </ul>
            </div>
            <div class="col-auto">
                <label class="sr-only" for="subscribeEmail">Email address</label>
                <div class="input-group mb-2">
                    <input type="text" class="form-control bg-light border-dark" id="subscribeEmail" placeholder="Email address">
                    <div class="input-group-text btn-success"><i class="fas fa-search"></i></div>
                </div>
            </div>
        </div>
    </div>

    <div class="w-100 bg-black py-3">
        <div class="container">
            <div class="row pt-2">
                <div class="col-12">
                    <p class="text-left">
                        Copyright &copy; 2021 Kahve
                        | Designed by Elif G. Uzgur
                    </p>
                </div>
            </div>
        </div>
    </div>

</footer>
<!-- End Footer -->

src/Web/Views/Shared/_LayoutHeaderPartial.cshtml
<nav class="navbar navbar-expand-lg" style="background-color: #d6b98d;">
    <a class="navbar-brand" asp-controller="Home" asp-action="Index">
        <img src="~/img/BrandLogo/Logo.png" alt="Logo" height="80" />
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    KAHVE
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: #f2e1c9 ">
                        @await Component.InvokeAsync("CategoryList")
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="about.html">HAKKIMIZDA</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="contact.html">İLETİŞİM</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                <i class="fas fa-search"></i>
            </button>
        </form>
        <partial name="_LoginPartial" />
        <vc:navbar-basket />
    </div>
</nav>

src/Web/Views/Shared/_LayoutPaginationPartial.cshtml
@model PaginationInfoViewModel

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item @(Model.HasPrevius ? "" : "disabled")">
            <a class="page-link" asp-all-route-data="GetRouteData(Model.Page - 1)">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>

        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            <li class="page-item">
                <a class="page-link" asp-all-route-data="GetRouteData(i)">@i</a>
            </li>

        }
        <li class="page-item @(Model.HasNext ? "" : "disabled")">
            <a class="page-link" asp-all-route-data="GetRouteData(Model.Page + 1)">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>

@{
    Dictionary<string, string> GetRouteData(int page)
    {
        var routeData = new Dictionary<string, string>();

        foreach (var item in Context.Request.Query)
        {
            if (item.Key == "page") continue;
            routeData.Add(item.Key, item.Value.ToString());
        }

        routeData.Add("page", page.ToString());
        return routeData;
    }
}